[package]
name = "fractal-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "fractal_rust"
crate-type = ["cdylib"]

[dependencies]
fractal-dsp = { path = "../fractal-dsp" }
pyo3 = { version = "0.23", features = ["extension-module"] }
numpy = "0.23"
serde_json.workspace = true
