[package]
name = "explore-dsp"
version = "0.1.0"
edition = "2021"

[dependencies]
rand.workspace = true
rand_chacha.workspace = true
realfft.workspace = true
num-complex.workspace = true
serde.workspace = true
serde_json.workspace = true
